const provider = $arguments.provider ?? "Provider",
  out = $arguments.out ?? "abbr",
  geoData = {
    "🇭🇰": { full: "Hong Kong", abbr: "HK" },
    "🇯🇵": { full: "Japan", abbr: "JP" },
    "🇸🇬": { full: "Singapore", abbr: "SG" },
    "🇺🇸": { full: "United States", abbr: "US" },
    "🇹🇼": { full: "Taiwan", abbr: "TW" },
    "🇨🇳": { full: "Taiwan", abbr: "TW" },
    "🇰🇷": { full: "South Korea", abbr: "KR" },
    "🇳🇱": { full: "Netherlands", abbr: "NL" },
    "🇩🇪": { full: "Germany", abbr: "DE" },
    "🇬🇧": { full: "United Kingdom", abbr: "GB" },
    "🇲🇴": { full: "Macao", abbr: "MO" },
    "🇫🇷": { full: "France", abbr: "FR" },
    "🇦🇺": { full: "Australia", abbr: "AU" },
    "🇦🇪": { full: "United Arab Emirates", abbr: "AE" },
    "🇦🇫": { full: "Afghanistan", abbr: "AF" },
    "🇦🇱": { full: "Albania", abbr: "AL" },
    "🇩🇿": { full: "Algeria", abbr: "DZ" },
    "🇦🇴": { full: "Angola", abbr: "AO" },
    "🇦🇷": { full: "Argentina", abbr: "AR" },
    "🇦🇲": { full: "Armenia", abbr: "AM" },
    "🇦🇹": { full: "Austria", abbr: "AT" },
    "🇦🇿": { full: "Azerbaijan", abbr: "AZ" },
    "🇧🇭": { full: "Bahrain", abbr: "BH" },
    "🇧🇩": { full: "Bangladesh", abbr: "BD" },
    "🇧🇾": { full: "Belarus", abbr: "BY" },
    "🇧🇪": { full: "Belgium", abbr: "BE" },
    "🇧🇿": { full: "Belize", abbr: "BZ" },
    "🇧🇯": { full: "Benin", abbr: "BJ" },
    "🇧🇹": { full: "Bhutan", abbr: "BT" },
    "🇧🇴": { full: "Bolivia", abbr: "BO" },
    "🇧🇦": { full: "Bosnia and Herzegovina", abbr: "BA" },
    "🇧🇼": { full: "Botswana", abbr: "BW" },
    "🇧🇷": { full: "Brazil", abbr: "BR" },
    "🇻🇬": { full: "British Virgin Islands", abbr: "VG" },
    "🇧🇳": { full: "Brunei", abbr: "BN" },
    "🇧🇬": { full: "Bulgaria", abbr: "BG" },
    "🇧🇫": { full: "Burkina Faso", abbr: "BF" },
    "🇧🇮": { full: "Burundi", abbr: "BI" },
    "🇰🇭": { full: "Cambodia", abbr: "KH" },
    "🇨🇲": { full: "Cameroon", abbr: "CM" },
    "🇨🇦": { full: "Canada", abbr: "CA" },
    "🇨🇻": { full: "Cape Verde", abbr: "CV" },
    "🇰🇾": { full: "Cayman Islands", abbr: "KY" },
    "🇨🇫": { full: "Central African Republic", abbr: "CF" },
    "🇹🇩": { full: "Chad", abbr: "TD" },
    "🇨🇱": { full: "Chile", abbr: "CL" },
    "🇨🇴": { full: "Colombia", abbr: "CO" },
    "🇰🇲": { full: "Comoros", abbr: "KM" },
    "🇨🇬": { full: "Congo - Brazzaville", abbr: "CG" },
    "🇨🇩": { full: "Congo - Kinshasa", abbr: "CD" },
    "🇨🇷": { full: "Costa Rica", abbr: "CR" },
    "🇭🇷": { full: "Croatia", abbr: "HR" },
    "🇨🇾": { full: "Cyprus", abbr: "CY" },
    "🇨🇿": { full: "Czechia", abbr: "CZ" },
    "🇩🇰": { full: "Denmark", abbr: "DK" },
    "🇩🇯": { full: "Djibouti", abbr: "DJ" },
    "🇩🇴": { full: "Dominican Republic", abbr: "DO" },
    "🇪🇨": { full: "Ecuador", abbr: "EC" },
    "🇪🇬": { full: "Egypt", abbr: "EG" },
    "🇸🇻": { full: "El Salvador", abbr: "SV" },
    "🇬🇶": { full: "Equatorial Guinea", abbr: "GQ" },
    "🇪🇷": { full: "Eritrea", abbr: "ER" },
    "🇪🇪": { full: "Estonia", abbr: "EE" },
    "🇪🇹": { full: "Ethiopia", abbr: "ET" },
    "🇫🇯": { full: "Fiji", abbr: "FJ" },
    "🇫🇮": { full: "Finland", abbr: "FI" },
    "🇬🇦": { full: "Gabon", abbr: "GA" },
    "🇬🇲": { full: "Gambia", abbr: "GM" },
    "🇬🇪": { full: "Georgia", abbr: "GE" },
    "🇬🇭": { full: "Ghana", abbr: "GH" },
    "🇬🇷": { full: "Greece", abbr: "GR" },
    "🇬🇱": { full: "Greenland", abbr: "GL" },
    "🇬🇹": { full: "Guatemala", abbr: "GT" },
    "🇬🇳": { full: "Guinea", abbr: "GN" },
    "🇬🇾": { full: "Guyana", abbr: "GY" },
    "🇭🇹": { full: "Haiti", abbr: "HT" },
    "🇭🇳": { full: "Honduras", abbr: "HN" },
    "🇭🇺": { full: "Hungary", abbr: "HU" },
    "🇮🇸": { full: "Iceland", abbr: "IS" },
    "🇮🇳": { full: "India", abbr: "IN" },
    "🇮🇩": { full: "Indonesia", abbr: "ID" },
    "🇮🇷": { full: "Iran", abbr: "IR" },
    "🇮🇶": { full: "Iraq", abbr: "IQ" },
    "🇮🇪": { full: "Ireland", abbr: "IE" },
    "🇮🇲": { full: "Isle of Man", abbr: "IM" },
    "🇮🇱": { full: "Israel", abbr: "IL" },
    "🇮🇹": { full: "Italy", abbr: "IT" },
    "🇨🇮": { full: "Côte d’Ivoire", abbr: "CI" },
    "🇯🇲": { full: "Jamaica", abbr: "JM" },
    "🇯🇴": { full: "Jordan", abbr: "JO" },
    "🇰🇿": { full: "Kazakhstan", abbr: "KZ" },
    "🇰🇪": { full: "Kenya", abbr: "KE" },
    "🇰🇼": { full: "Kuwait", abbr: "KW" },
    "🇰🇬": { full: "Kyrgyzstan", abbr: "KG" },
    "🇱🇦": { full: "Laos", abbr: "LA" },
    "🇱🇻": { full: "Latvia", abbr: "LV" },
    "🇱🇧": { full: "Lebanon", abbr: "LB" },
    "🇱🇸": { full: "Lesotho", abbr: "LS" },
    "🇱🇷": { full: "Liberia", abbr: "LR" },
    "🇱🇾": { full: "Libya", abbr: "LY" },
    "🇱🇹": { full: "Lithuania", abbr: "LT" },
    "🇱🇺": { full: "Luxembourg", abbr: "LU" },
    "🇲🇰": { full: "North Macedonia", abbr: "MK" },
    "🇲🇬": { full: "Madagascar", abbr: "MG" },
    "🇲🇼": { full: "Malawi", abbr: "MW" },
    "🇲🇾": { full: "Malaysia", abbr: "MY" },
    "🇲🇻": { full: "Maldives", abbr: "MV" },
    "🇲🇱": { full: "Mali", abbr: "ML" },
    "🇲🇹": { full: "Malta", abbr: "MT" },
    "🇲🇷": { full: "Mauritania", abbr: "MR" },
    "🇲🇺": { full: "Mauritius", abbr: "MU" },
    "🇲🇽": { full: "Mexico", abbr: "MX" },
    "🇲🇩": { full: "Moldova", abbr: "MD" },
    "🇲🇨": { full: "Monaco", abbr: "MC" },
    "🇲🇳": { full: "Mongolia", abbr: "MN" },
    "🇲🇪": { full: "Montenegro", abbr: "ME" },
    "🇲🇦": { full: "Morocco", abbr: "MA" },
    "🇲🇿": { full: "Mozambique", abbr: "MZ" },
    "🇲🇲": { full: "Myanmar", abbr: "MM" },
    "🇳🇦": { full: "Namibia", abbr: "NA" },
    "🇳🇵": { full: "Nepal", abbr: "NP" },
    "🇳🇿": { full: "New Zealand", abbr: "NZ" },
    "🇳🇮": { full: "Nicaragua", abbr: "NI" },
    "🇳🇪": { full: "Niger", abbr: "NE" },
    "🇳🇬": { full: "Nigeria", abbr: "NG" },
    "🇰🇵": { full: "North Korea", abbr: "KP" },
    "🇳🇴": { full: "Norway", abbr: "NO" },
    "🇴🇲": { full: "Oman", abbr: "OM" },
    "🇵🇰": { full: "Pakistan", abbr: "PK" },
    "🇵🇦": { full: "Panama", abbr: "PA" },
    "🇵🇾": { full: "Paraguay", abbr: "PY" },
    "🇵🇪": { full: "Peru", abbr: "PE" },
    "🇵🇭": { full: "Philippines", abbr: "PH" },
    "🇵🇹": { full: "Portugal", abbr: "PT" },
    "🇵🇷": { full: "Puerto Rico", abbr: "PR" },
    "🇶🇦": { full: "Qatar", abbr: "QA" },
    "🇷🇴": { full: "Romania", abbr: "RO" },
    "🇷🇺": { full: "Russia", abbr: "RU" },
    "🇷🇼": { full: "Rwanda", abbr: "RW" },
    "🇸🇲": { full: "San Marino", abbr: "SM" },
    "🇸🇦": { full: "Saudi Arabia", abbr: "SA" },
    "🇸🇳": { full: "Senegal", abbr: "SN" },
    "🇷🇸": { full: "Serbia", abbr: "RS" },
    "🇸🇱": { full: "Sierra Leone", abbr: "SL" },
    "🇸🇰": { full: "Slovakia", abbr: "SK" },
    "🇸🇮": { full: "Slovenia", abbr: "SI" },
    "🇸🇴": { full: "Somalia", abbr: "SO" },
    "🇿🇦": { full: "South Africa", abbr: "ZA" },
    "🇪🇸": { full: "Spain", abbr: "ES" },
    "🇱🇰": { full: "Sri Lanka", abbr: "LK" },
    "🇸🇩": { full: "Sudan", abbr: "SD" },
    "🇸🇷": { full: "Suriname", abbr: "SR" },
    "🇸🇿": { full: "Eswatini", abbr: "SZ" },
    "🇸🇪": { full: "Sweden", abbr: "SE" },
    "🇨🇭": { full: "Switzerland", abbr: "CH" },
    "🇸🇾": { full: "Syria", abbr: "SY" },
    "🇹🇯": { full: "Tajikistan", abbr: "TJ" },
    "🇹🇿": { full: "Tanzania", abbr: "TZ" },
    "🇹🇭": { full: "Thailand", abbr: "TH" },
    "🇹🇬": { full: "Togo", abbr: "TG" },
    "🇹🇴": { full: "Tonga", abbr: "TO" },
    "🇹🇹": { full: "Trinidad and Tobago", abbr: "TT" },
    "🇹🇳": { full: "Tunisia", abbr: "TN" },
    "🇹🇷": { full: "Turkey", abbr: "TR" },
    "🇹🇲": { full: "Turkmenistan", abbr: "TM" },
    "🇻🇮": { full: "U.S. Virgin Islands", abbr: "VI" },
    "🇺🇬": { full: "Uganda", abbr: "UG" },
    "🇺🇦": { full: "Ukraine", abbr: "UA" },
    "🇺🇾": { full: "Uruguay", abbr: "UY" },
    "🇺🇿": { full: "Uzbekistan", abbr: "UZ" },
    "🇻🇪": { full: "Venezuela", abbr: "VE" },
    "🇻🇳": { full: "Vietnam", abbr: "VN" },
    "🇾🇪": { full: "Yemen", abbr: "YE" },
    "🇿🇲": { full: "Zambia", abbr: "ZM" },
    "🇿🇼": { full: "Zimbabwe", abbr: "ZW" },
    "🇦🇩": { full: "Andorra", abbr: "AD" },
    "🇷🇪": { full: "Réunion", abbr: "RE" },
    "🇵🇱": { full: "Poland", abbr: "PL" },
    "🇬🇺": { full: "Guam", abbr: "GU" },
    "🇻🇦": { full: "Vatican City", abbr: "VA" },
    "🇱🇮": { full: "Liechtenstein", abbr: "LI" },
    "🇨🇼": { full: "Curaçao", abbr: "CW" },
    "🇸🇨": { full: "Seychelles", abbr: "SC" },
    "🇦🇶": { full: "Antarctica", abbr: "AQ" },
    "🇬🇮": { full: "Gibraltar", abbr: "GI" },
    "🇨🇺": { full: "Cuba", abbr: "CU" },
    "🇫🇴": { full: "Faroe Islands", abbr: "FO" },
    "🇦🇽": { full: "Åland Islands", abbr: "AX" },
    "🇧🇲": { full: "Bermuda", abbr: "BM" },
    "🇹🇱": { full: "Timor-Leste", abbr: "TL" },
  },
  abMap = Object.values(geoData).reduce((m, o) => ((m[o.abbr] = o), m), {});

const flag = $server.name.match(/^[\u{1F1E6}-\u{1F1FF}]{2}/u)?.[0] || "",
  words = [
    ...new Intl.Segmenter(undefined, { granularity: "word" }).segment(
      $server.name.replace(flag, "").trim()
    ),
  ]
    .filter((s) => s.isWordLike || /[-.]/.test(s.segment))
    .map((s) => s.segment),
  country =
    flag && geoData[flag]
      ? geoData[flag][out]
      : words[0]
      ? abMap[words[0].slice(0, 2).toUpperCase()]?.[out]
      : "",
  processed = [provider + " " + country].concat(
    words.slice(1).filter((x) => !/ˣ|\b(x\d+|\d+x)/i.test(x.replace(/ˣ/g, "")))
  );

$server.name =
  flag +
  " " +
  processed.reduce((a, c) =>
    /[-.]$/.test(a) || /^[-.]/.test(c) ? a + c : a + " " + c
  );
